In [258]:
import pandas as pd
import numpy as np
df = pd.read_csv("penguins.csv")

In [259]:
df.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007

In [260]:
df.tail(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
334,Chinstrap,Dream,50.2,18.8,202.0,3800.0,male,2009
335,Chinstrap,Dream,45.6,19.4,194.0,3525.0,female,2009
336,Chinstrap,Dream,51.9,19.5,206.0,3950.0,male,2009
337,Chinstrap,Dream,46.8,16.5,189.0,3650.0,female,2009
338,Chinstrap,Dream,45.7,17.0,195.0,3650.0,female,2009
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [261]:
print("rows =", df.index.stop + 1)
df.index

rows = 345

RangeIndex(start=0, stop=344, step=1)

In [262]:
print("columns = ", len(df.columns))
df.columns

columns =  8

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='str')

In [263]:
for col in df.columns:
    print(f"{col} [{df[col].dtype}]")

species [str]
island [str]
bill_length_mm [float64]
bill_depth_mm [float64]
flipper_length_mm [float64]
body_mass_g [float64]
sex [str]
year [int64]

In [264]:
df.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,342.000000,342.000000,342.000000,342.000000,344.000000
mean,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,5.459584,1.974793,14.061714,801.954536,0.818356
min,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,59.600000,21.500000,231.000000,6300.000000,2009.000000

In [265]:
print("NaN values per columns\n")
for col in df.columns:
    print(f"{col} {df[col].isna().value_counts().values}\n")

NaN values per columns

species [344]

island [344]

bill_length_mm [342   2]

bill_depth_mm [342   2]

flipper_length_mm [342   2]

body_mass_g [342   2]

sex [333  11]

year [344]

In [266]:
df["species"]

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...
339    Chinstrap
340    Chinstrap
341    Chinstrap
342    Chinstrap
343    Chinstrap
Name: species, Length: 344, dtype: str

In [267]:
df.loc[:, ["species", "island", "body_mass_g"]]

       species     island  body_mass_g
0       Adelie  Torgersen       3750.0
1       Adelie  Torgersen       3800.0
2       Adelie  Torgersen       3250.0
3       Adelie  Torgersen          NaN
4       Adelie  Torgersen       3450.0
..         ...        ...          ...
339  Chinstrap      Dream       4000.0
340  Chinstrap      Dream       3400.0
341  Chinstrap      Dream       3775.0
342  Chinstrap      Dream       4100.0
343  Chinstrap      Dream       3775.0

[344 rows x 3 columns]

In [268]:
df.loc[5]

species                 Adelie
island               Torgersen
bill_length_mm            39.3
bill_depth_mm             20.6
flipper_length_mm        190.0
body_mass_g             3650.0
sex                       male
year                      2007
Name: 5, dtype: object

In [269]:
df.loc[10:20]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,2007
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,female,2007
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,male,2007
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,male,2007
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,female,2007
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,male,2007
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,female,2007
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,male,2007
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,female,2007

In [270]:
df.loc[:15, ["bill_length_mm", "bill_depth_mm"]]

    bill_length_mm  bill_depth_mm
0             39.1           18.7
1             39.5           17.4
2             40.3           18.0
3              NaN            NaN
4             36.7           19.3
5             39.3           20.6
6             38.9           17.8
7             39.2           19.6
8             34.1           18.1
9             42.0           20.2
10            37.8           17.1
11            37.8           17.3
12            41.1           17.6
13            38.6           21.2
14            34.6           21.1
15            36.6           17.8

In [271]:
df[df["body_mass_g"] > 5000]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
159,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
161,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
...,...,...,...,...,...,...,...,...
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [272]:
df[df["species"] == "Adelie"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,female,2009
148,Adelie,Dream,36.0,17.8,195.0,3450.0,female,2009
149,Adelie,Dream,37.8,18.1,193.0,3750.0,male,2009
150,Adelie,Dream,36.0,17.1,187.0,3700.0,female,2009
151,Adelie,Dream,41.5,18.5,201.0,4000.0,male,2009

In [273]:
df_tmp = df[df["species"] == "Gentoo"]
df_tmp = df_tmp[df_tmp["body_mass_g"] > 5500]
df_tmp[df_tmp["bill_depth_mm"] > 16]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
163,Gentoo,Biscoe,49.0,16.1,216.0,5550.0,male,2007
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007
217,Gentoo,Biscoe,49.8,16.8,230.0,5700.0,male,2008
219,Gentoo,Biscoe,49.5,16.2,229.0,5800.0,male,2008
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008
231,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,male,2008
237,Gentoo,Biscoe,50.8,17.3,228.0,5600.0,male,2009
241,Gentoo,Biscoe,52.1,17.0,230.0,5550.0,male,2009
245,Gentoo,Biscoe,49.5,16.1,224.0,5650.0,male,2009
253,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009

In [274]:
df_tmp2 = df.copy()
df_tmp2["body_mass_kg"] = (df_tmp2["body_mass_g"] / 1000).round(2)
df_tmp2

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.75
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.80
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.25
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.45
...,...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009,4.00
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009,3.40
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009,3.78
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009,4.10
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009,3.78

In [275]:
df_tmp3 = df.copy()
df_tmp3["bill_ratio"] = (df_tmp3["bill_length_mm"] / df["bill_depth_mm"]).round(3)
df_tmp3

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,2.091
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,2.270
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,2.239
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,1.902
...,...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009,2.818
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009,2.403
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009,2.725
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009,2.674
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009,2.684

In [276]:
def category(x):
    if x < 4000:
        return "light"
    elif x >= 4000 and x < 5000:
        return "medium"
    elif x >= 5000:
        return "heavy"
    else:
        return None

df_tmp4 = df.copy()
df_tmp4["body_mass_category"] = df_tmp4["body_mass_g"].apply(category)
df_tmp4

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_category
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,light
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,light
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,light
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,light
...,...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009,medium
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009,light
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009,light
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009,medium
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009,light

In [277]:
df_tmp4.sort_values("body_mass_g")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_category
314,Chinstrap,Dream,46.9,16.6,192.0,2700.0,female,2008,light
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,female,2008,light
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,female,2008,light
54,Adelie,Biscoe,34.5,18.1,187.0,2900.0,female,2008,light
98,Adelie,Dream,33.1,16.1,178.0,2900.0,female,2008,light
...,...,...,...,...,...,...,...,...,...
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008,heavy
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007,heavy
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007,heavy
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009,NaN

In [278]:
df_tmp4.nlargest(10, "body_mass_g")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_category
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007,heavy
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007,heavy
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008,heavy
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009,heavy
231,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,male,2008,heavy
263,Gentoo,Biscoe,49.8,15.9,229.0,5950.0,male,2009,heavy
165,Gentoo,Biscoe,48.4,14.6,213.0,5850.0,male,2007,heavy
167,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,male,2007,heavy
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009,heavy
219,Gentoo,Biscoe,49.5,16.2,229.0,5800.0,male,2008,heavy

In [279]:
df.groupby("species")[["body_mass_g"]].mean()

           body_mass_g
species
Adelie     3700.662252
Chinstrap  3733.088235
Gentoo     5076.016260

In [280]:
df.groupby("species")[["body_mass_g"]].max()

           body_mass_g
species
Adelie          4775.0
Chinstrap       4800.0
Gentoo          6300.0

In [281]:
df.groupby("species")[["body_mass_g"]].min()

           body_mass_g
species
Adelie          2850.0
Chinstrap       2700.0
Gentoo          3950.0

In [282]:
df.groupby("island")[["flipper_length_mm"]].mean()

           flipper_length_mm
island
Biscoe            209.706587
Dream             193.072581
Torgersen         191.196078

In [283]:
df.groupby(["species", "sex"])[["body_mass_g"]].mean()

                  body_mass_g
species   sex
Adelie    female  3368.835616
          male    4043.493151
Chinstrap female  3527.205882
          male    3938.970588
Gentoo    female  4679.741379
          male    5484.836066

In [284]:
df.value_counts("species")

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [285]:
df.value_counts("island")

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [286]:
df.value_counts(["species", "sex"])

species    sex
Adelie     male      73
           female    73
Gentoo     male      61
           female    58
Chinstrap  female    34
           male      34
Name: count, dtype: int64

In [287]:
df[df.isna().any(axis=1)]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,2007
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN,2007
178,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN,2007
218,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN,2008
256,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN,2009
268,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN,2009
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009

In [288]:
df_tmp5 = df.dropna()
df_tmp5[df_tmp5.isna().any(axis=1)]

Empty DataFrame
Columns: [species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year]
Index: []

In [289]:
df_tmp6 = df.copy()
df_tmp6.fillna({"sex":"unknown"}, inplace=True)
df_tmp6

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,unknown,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [290]:
df_tmp6.fillna({"bill_length_mm": df_tmp6["bill_length_mm"].mean()}, inplace=True)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.10000,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.50000,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.30000,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,43.92193,NaN,NaN,NaN,unknown,2007
4,Adelie,Torgersen,36.70000,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80000,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.50000,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.60000,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.80000,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.20000,18.7,198.0,3775.0,female,2009

In [291]:
df_tmp6

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.10000,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.50000,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.30000,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,43.92193,NaN,NaN,NaN,unknown,2007
4,Adelie,Torgersen,36.70000,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80000,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.50000,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.60000,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.80000,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.20000,18.7,198.0,3775.0,female,2009

In [292]:
def g_to_kg(x):
    return x/1000

df_tmp6["body_mass_g"] = df_tmp6["body_mass_g"].apply(g_to_kg)
df_tmp6.rename(columns={"body_mass_g":"body_mass_kg"}, inplace=True)
df_tmp6

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg,sex,year
0,Adelie,Torgersen,39.10000,18.7,181.0,3.750,male,2007
1,Adelie,Torgersen,39.50000,17.4,186.0,3.800,female,2007
2,Adelie,Torgersen,40.30000,18.0,195.0,3.250,female,2007
3,Adelie,Torgersen,43.92193,NaN,NaN,NaN,unknown,2007
4,Adelie,Torgersen,36.70000,19.3,193.0,3.450,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80000,19.8,207.0,4.000,male,2009
340,Chinstrap,Dream,43.50000,18.1,202.0,3.400,female,2009
341,Chinstrap,Dream,49.60000,18.2,193.0,3.775,male,2009
342,Chinstrap,Dream,50.80000,19.0,210.0,4.100,male,2009
343,Chinstrap,Dream,50.20000,18.7,198.0,3.775,female,2009

In [293]:
def round_2cases(x):
    return round(x, 2)

df_tmp6 = df_tmp6.apply(round_2cases)
df_tmp6

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg,sex,year
0,Adelie,Torgersen,39.10,18.7,181.0,3.75,male,2007
1,Adelie,Torgersen,39.50,17.4,186.0,3.80,female,2007
2,Adelie,Torgersen,40.30,18.0,195.0,3.25,female,2007
3,Adelie,Torgersen,43.92,NaN,NaN,NaN,unknown,2007
4,Adelie,Torgersen,36.70,19.3,193.0,3.45,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80,19.8,207.0,4.00,male,2009
340,Chinstrap,Dream,43.50,18.1,202.0,3.40,female,2009
341,Chinstrap,Dream,49.60,18.2,193.0,3.78,male,2009
342,Chinstrap,Dream,50.80,19.0,210.0,4.10,male,2009
343,Chinstrap,Dream,50.20,18.7,198.0,3.78,female,2009

In [294]:
def min_cases(x):
    return x.lower()

df_tmp6["species"] = df_tmp6["species"].apply(min_cases)
df_tmp6

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg,sex,year
0,adelie,Torgersen,39.10,18.7,181.0,3.75,male,2007
1,adelie,Torgersen,39.50,17.4,186.0,3.80,female,2007
2,adelie,Torgersen,40.30,18.0,195.0,3.25,female,2007
3,adelie,Torgersen,43.92,NaN,NaN,NaN,unknown,2007
4,adelie,Torgersen,36.70,19.3,193.0,3.45,female,2007
...,...,...,...,...,...,...,...,...
339,chinstrap,Dream,55.80,19.8,207.0,4.00,male,2009
340,chinstrap,Dream,43.50,18.1,202.0,3.40,female,2009
341,chinstrap,Dream,49.60,18.2,193.0,3.78,male,2009
342,chinstrap,Dream,50.80,19.0,210.0,4.10,male,2009
343,chinstrap,Dream,50.20,18.7,198.0,3.78,female,2009

In [295]:
df_tmp6.set_index("species", inplace=True)
df_tmp6

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg,sex,year
species,,,,,,,
adelie,Torgersen,39.10,18.7,181.0,3.75,male,2007
adelie,Torgersen,39.50,17.4,186.0,3.80,female,2007
adelie,Torgersen,40.30,18.0,195.0,3.25,female,2007
adelie,Torgersen,43.92,NaN,NaN,NaN,unknown,2007
adelie,Torgersen,36.70,19.3,193.0,3.45,female,2007
...,...,...,...,...,...,...,...
chinstrap,Dream,55.80,19.8,207.0,4.00,male,2009
chinstrap,Dream,43.50,18.1,202.0,3.40,female,2009
chinstrap,Dream,49.60,18.2,193.0,3.78,male,2009
chinstrap,Dream,50.80,19.0,210.0,4.10,male,2009
chinstrap,Dream,50.20,18.7,198.0,3.78,female,2009

In [296]:
df_tmp6.reset_index()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg,sex,year
0,adelie,Torgersen,39.10,18.7,181.0,3.75,male,2007
1,adelie,Torgersen,39.50,17.4,186.0,3.80,female,2007
2,adelie,Torgersen,40.30,18.0,195.0,3.25,female,2007
3,adelie,Torgersen,43.92,NaN,NaN,NaN,unknown,2007
4,adelie,Torgersen,36.70,19.3,193.0,3.45,female,2007
...,...,...,...,...,...,...,...,...
339,chinstrap,Dream,55.80,19.8,207.0,4.00,male,2009
340,chinstrap,Dream,43.50,18.1,202.0,3.40,female,2009
341,chinstrap,Dream,49.60,18.2,193.0,3.78,male,2009
342,chinstrap,Dream,50.80,19.0,210.0,4.10,male,2009
343,chinstrap,Dream,50.20,18.7,198.0,3.78,female,2009

In [297]:
df["body_mass_g"].mean()

np.float64(4201.754385964912)

In [298]:
df["bill_length_mm"].std()

np.float64(5.4595837139265315)

In [299]:
df_tmp7 = df.loc[:, ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]]
df_tmp7.corr(numeric_only=True)

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,1.000000,-0.235053,0.656181,0.595110
bill_depth_mm,-0.235053,1.000000,-0.583851,-0.471916
flipper_length_mm,0.656181,-0.583851,1.000000,0.871202
body_mass_g,0.595110,-0.471916,0.871202,1.000000

In [300]:
df.sample(20)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
270,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,female,2009
181,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,male,2007
338,Chinstrap,Dream,45.7,17.0,195.0,3650.0,female,2009
176,Gentoo,Biscoe,42.9,13.1,215.0,5000.0,female,2007
48,Adelie,Dream,36.0,17.9,190.0,3450.0,female,2007
245,Gentoo,Biscoe,49.5,16.1,224.0,5650.0,male,2009
123,Adelie,Torgersen,41.4,18.5,202.0,3875.0,male,2009
116,Adelie,Torgersen,38.6,17.0,188.0,2900.0,female,2009
305,Chinstrap,Dream,52.8,20.0,205.0,4550.0,male,2008
239,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,male,2009
144,Adelie,Dream,37.3,16.8,192.0,3000.0,female,2009
247,Gentoo,Biscoe,50.8,15.7,226.0,5200.0,male,2009
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
286,Chinstrap,Dream,46.6,17.8,193.0,3800.0,female,2007
320,Chinstrap,Dream,50.9,17.9,196.0,3675.0,female,2009
157,Gentoo,Biscoe,46.5,13.5,210.0,4550.0,female,2007
182,Gentoo,Biscoe,47.3,15.3,222.0,5250.0,male,2007
226,Gentoo,Biscoe,46.4,15.0,216.0,4700.0,female,2008
302,Chinstrap,Dream,50.5,18.4,200.0,3400.0,female,2008
160,Gentoo,Biscoe,43.3,13.4,209.0,4400.0,female,2007

In [301]:
df.sample(frac=0.1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
27,Adelie,Biscoe,40.5,17.9,187.0,3200.0,female,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
220,Gentoo,Biscoe,43.5,14.2,220.0,4700.0,female,2008
35,Adelie,Dream,39.2,21.1,196.0,4150.0,male,2007
187,Gentoo,Biscoe,48.4,16.3,220.0,5400.0,male,2008
272,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
312,Chinstrap,Dream,47.6,18.3,195.0,3850.0,female,2008
28,Adelie,Biscoe,37.9,18.6,172.0,3150.0,female,2007
306,Chinstrap,Dream,40.9,16.6,187.0,3200.0,female,2008
300,Chinstrap,Dream,46.7,17.9,195.0,3300.0,female,2007
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,female,2007
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
48,Adelie,Dream,36.0,17.9,190.0,3450.0,female,2007
193,Gentoo,Biscoe,49.6,16.0,225.0,5700.0,male,2008
112,Adelie,Biscoe,39.7,17.7,193.0,3200.0,female,2009
198,Gentoo,Biscoe,45.5,13.9,210.0,4200.0,female,2008
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,female,2007
144,Adelie,Dream,37.3,16.8,192.0,3000.0,female,2009
205,Gentoo,Biscoe,50.1,15.0,225.0,5000.0,male,2008
282,Chinstrap,Dream,46.1,18.2,178.0,3250.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007
140,Adelie,Dream,40.2,17.1,193.0,3400.0,female,2009
256,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN,2009
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,male,2007
30,Adelie,Dream,39.5,16.7,178.0,3250.0,female,2007
210,Gentoo,Biscoe,43.2,14.5,208.0,4450.0,female,2008
276,Chinstrap,Dream,46.5,17.9,192.0,3500.0,female,2007
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
240,Gentoo,Biscoe,47.5,14.0,212.0,4875.0,female,2009
288,Chinstrap,Dream,47.0,17.3,185.0,3700.0,female,2007
266,Gentoo,Biscoe,46.2,14.1,217.0,4375.0,female,2009
148,Adelie,Dream,36.0,17.8,195.0,3450.0,female,2009

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Length: 344, dtype: bool

In [306]:
df_tmp8 = df.copy()
df_tmp8.drop_duplicates()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [308]:
df.sort_values("body_mass_g", ascending=False)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008
231,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,male,2008
...,...,...,...,...,...,...,...,...
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,female,2008
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,female,2008
314,Chinstrap,Dream,46.9,16.6,192.0,2700.0,female,2008
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009

In [312]:
df.query('species == "Adelie" and body_mass_g > 4000')

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,male,2007
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,male,2007
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,male,2007
35,Adelie,Dream,39.2,21.1,196.0,4150.0,male,2007
39,Adelie,Dream,39.8,19.1,184.0,4650.0,male,2007
43,Adelie,Dream,44.1,19.7,196.0,4400.0,male,2007
45,Adelie,Dream,39.6,18.8,190.0,4600.0,male,2007
49,Adelie,Dream,42.3,21.2,191.0,4150.0,male,2007
51,Adelie,Biscoe,40.1,18.9,188.0,4300.0,male,2008
53,Adelie,Biscoe,42.0,19.5,200.0,4050.0,male,2008
61,Adelie,Biscoe,41.3,21.1,195.0,4400.0,male,2008
63,Adelie,Biscoe,41.1,18.2,192.0,4050.0,male,2008
67,Adelie,Biscoe,41.1,19.1,188.0,4100.0,male,2008
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,male,2008
73,Adelie,Torgersen,45.8,18.9,197.0,4150.0,male,2008
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,male,2008
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,male,2008
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,male,2008
91,Adelie,Dream,41.1,18.1,205.0,4300.0,male,2008
93,Adelie,Dream,39.6,18.1,186.0,4450.0,male,2008
95,Adelie,Dream,40.8,18.9,208.0,4300.0,male,2008
97,Adelie,Dream,40.3,18.5,196.0,4350.0,male,2008
99,Adelie,Dream,43.2,18.5,192.0,4100.0,male,2008
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,male,2009
103,Adelie,Biscoe,37.8,20.0,190.0,4250.0,male,2009
109,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009
111,Adelie,Biscoe,45.6,20.3,191.0,4600.0,male,2009
113,Adelie,Biscoe,42.2,19.5,197.0,4275.0,male,2009
115,Adelie,Biscoe,42.7,18.3,196.0,4075.0,male,2009
127,Adelie,Torgersen,41.5,18.3,195.0,4300.0,male,2009
133,Adelie,Dream,37.5,18.5,199.0,4475.0,male,2009
139,Adelie,Dream,39.7,17.9,193.0,4250.0,male,2009
146,Adelie,Dream,39.2,18.6,190.0,4250.0,male,2009

In [313]:
pd.pivot_table(df, values="body_mass_g", index=["species"], columns=["island"], aggfunc="mean")

island          Biscoe        Dream    Torgersen
species
Adelie     3709.659091  3688.392857  3706.372549
Chinstrap          NaN  3733.088235          NaN
Gentoo     5076.016260          NaN          NaN

In [315]:
df_tmp9 = df.copy()
df_tmp9 = df.loc[:, ["species", "island", "sex", "body_mass_g", "flipper_length_mm", "bill_length_mm", "bill_depth_mm", "year"]]
df_tmp9

,species,island,sex,body_mass_g,flipper_length_mm,bill_length_mm,bill_depth_mm,year
0,Adelie,Torgersen,male,3750.0,181.0,39.1,18.7,2007
1,Adelie,Torgersen,female,3800.0,186.0,39.5,17.4,2007
2,Adelie,Torgersen,female,3250.0,195.0,40.3,18.0,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,female,3450.0,193.0,36.7,19.3,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,male,4000.0,207.0,55.8,19.8,2009
340,Chinstrap,Dream,female,3400.0,202.0,43.5,18.1,2009
341,Chinstrap,Dream,male,3775.0,193.0,49.6,18.2,2009
342,Chinstrap,Dream,male,4100.0,210.0,50.8,19.0,2009
343,Chinstrap,Dream,female,3775.0,198.0,50.2,18.7,2009